/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 04:59:33 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(11, 12, 12, 12, 12, "", "");
      String string0 = appt0.toString();
      assertNotNull(string0);
      assertEquals("\t12/12/12 at 11:12am ,, \n", string0);
      assertTrue(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 82, 23, 82, "hV!`nJZ,", "hV!`nJZ,");
      assertEquals(23, appt0.getStartHour());
      assertEquals(82, appt0.getStartDay());
      assertEquals(23, appt0.getStartMonth());
      assertEquals("hV!`nJZ,", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals("hV!`nJZ,", appt0.getDescription());
      assertEquals(82, appt0.getStartYear());
      assertEquals(23, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(12, 23, 12, 4, 4, "", "");
      boolean boolean0 = appt0.getValid();
      assertEquals(4, appt0.getStartYear());
      assertEquals(23, appt0.getStartMinute());
      assertTrue(boolean0);
      assertEquals(12, appt0.getStartHour());
      assertEquals(12, appt0.getStartDay());
      assertEquals(4, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt(178, 178, 178, 0, 178, "", "");
      appt0.getTitle();
      assertEquals(178, appt0.getStartYear());
      assertEquals(178, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(178, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(178, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, (-2179), 0, "", "");
      int int0 = appt0.getStartYear();
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, int0);
      assertEquals(-2179, appt0.getStartMonth());
      assertEquals(0, appt0.getStartHour());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt(16, 16, 16, 16, 16, "T@", "T@");
      int int0 = appt0.getStartYear();
      assertEquals(16, appt0.getStartHour());
      assertEquals(16, appt0.getStartMinute());
      assertEquals(16, appt0.getStartMonth());
      assertEquals("T@", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(16, appt0.getStartDay());
      assertEquals("T@", appt0.getDescription());
      assertEquals(16, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt((-2022), (-2022), 2047, 0, 0, "KxSec f1:)jDlRuH5", "KxSec f1:)jDlRuH5");
      int int0 = appt0.getStartMonth();
      assertFalse(appt0.getValid());
      assertEquals(0, int0);
      assertEquals(2047, appt0.getStartDay());
      assertEquals("KxSec f1:)jDlRuH5", appt0.getDescription());
      assertEquals(0, appt0.getStartYear());
      assertEquals(-2022, appt0.getStartMinute());
      assertEquals(-2022, appt0.getStartHour());
      assertEquals("KxSec f1:)jDlRuH5", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt(475, 475, (-2656), (-1090), 475, "-\"V~BOE*pQ", "-\"V~BOE*pQ");
      int int0 = appt0.getStartMonth();
      assertEquals(475, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals("-\"V~BOE*pQ", appt0.getTitle());
      assertEquals(-2656, appt0.getStartDay());
      assertEquals(475, appt0.getStartYear());
      assertEquals((-1090), int0);
      assertEquals(475, appt0.getStartHour());
      assertEquals("-\"V~BOE*pQ", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(692, 0, 31, 0, 0, "a[t6-jCi", "a[t6-jCi");
      int int0 = appt0.getStartMinute();
      assertEquals("a[t6-jCi", appt0.getDescription());
      assertEquals(0, appt0.getStartYear());
      assertEquals("a[t6-jCi", appt0.getTitle());
      assertEquals(31, appt0.getStartDay());
      assertEquals(692, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt(0, 59, 2393, 0, 1959, "", "");
      int int0 = appt0.getStartMinute();
      assertEquals(59, int0);
      assertEquals(0, appt0.getStartMonth());
      assertEquals(2393, appt0.getStartDay());
      assertEquals(0, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(1959, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(0, 444, 3075, 3075, 3075, "", "");
      int int0 = appt0.getStartHour();
      assertEquals(3075, appt0.getStartDay());
      assertEquals(0, int0);
      assertFalse(appt0.getValid());
      assertEquals(3075, appt0.getStartYear());
      assertEquals(444, appt0.getStartMinute());
      assertEquals(3075, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(1474, 1474, 31, 0, 15, "", "");
      int int0 = appt0.getStartHour();
      assertEquals(1474, int0);
      assertEquals(0, appt0.getStartMonth());
      assertEquals(1474, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(31, appt0.getStartDay());
      assertEquals(15, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt(2196, (-2068), 0, (-1659), 0, "", (String) null);
      int int0 = appt0.getStartDay();
      assertEquals(0, int0);
      assertEquals(-2068, appt0.getStartMinute());
      assertEquals(-1659, appt0.getStartMonth());
      assertEquals(2196, appt0.getStartHour());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt(11, 12, 12, 12, 12, "", "");
      appt0.getDescription();
      assertEquals(12, appt0.getStartYear());
      assertEquals(12, appt0.getStartMonth());
      assertEquals(12, appt0.getStartDay());
      assertTrue(appt0.getValid());
      assertEquals(11, appt0.getStartHour());
      assertEquals(12, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(0, 59, 2393, 0, 1959, "", "");
      appt0.setDescription("!K7F\raWW~fU}7Ne");
      assertEquals("!K7F\raWW~fU}7Ne", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt(11, 12, 12, 12, 12, "", "");
      appt0.setDescription((String) null);
      assertEquals(12, appt0.getStartMinute());
      assertEquals(12, appt0.getStartMonth());
      assertTrue(appt0.getValid());
      assertEquals(12, appt0.getStartDay());
      assertEquals(11, appt0.getStartHour());
      assertEquals(12, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt((-2022), (-2022), 2047, 0, 0, "KxSec f1:)jDlRuH5", "KxSec f1:)jDlRuH5");
      appt0.setTitle("KxSec f1:)jDlRuH5");
      assertEquals(-2022, appt0.getStartHour());
      assertEquals(-2022, appt0.getStartMinute());
      assertEquals(2047, appt0.getStartDay());
      assertEquals(0, appt0.getStartMonth());
      assertFalse(appt0.getValid());
      assertEquals("KxSec f1:)jDlRuH5", appt0.getTitle());
      assertEquals(0, appt0.getStartYear());
      assertEquals("KxSec f1:)jDlRuH5", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 0, 0, 11, "", "");
      appt0.setStartMinute(89);
      assertEquals(89, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt((-1859), (-1859), (-1859), (-1859), (-1859), "oG\"", "oG\"");
      String string0 = appt0.getTitle();
      assertEquals("oG\"", appt0.getDescription());
      assertEquals(-1859, appt0.getStartYear());
      assertEquals(-1859, appt0.getStartHour());
      assertEquals("oG\"", string0);
      assertEquals(-1859, appt0.getStartMonth());
      assertFalse(appt0.getValid());
      assertEquals(-1859, appt0.getStartDay());
      assertEquals(-1859, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 60, (-196), 31, "K)Hk", "K)Hk");
      int int0 = appt0.getStartDay();
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(60, int0);
      assertEquals("K)Hk", appt0.getTitle());
      assertEquals(-196, appt0.getStartMonth());
      assertEquals(31, appt0.getStartYear());
      assertEquals(0, appt0.getStartHour());
      assertEquals("K)Hk", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt((-122), (-1227), (-1227), (-122), (-1227), "%+}s-(S", "%+}s-(S");
      boolean boolean0 = appt0.getValid();
      assertEquals(-1227, appt0.getStartMinute());
      assertEquals(-122, appt0.getStartMonth());
      assertEquals(-122, appt0.getStartHour());
      assertEquals(-1227, appt0.getStartYear());
      assertEquals("%+}s-(S", appt0.getDescription());
      assertEquals("%+}s-(S", appt0.getTitle());
      assertFalse(boolean0);
      assertEquals(-1227, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt((-3149), (-3149), (-3149), (-3149), (-2266), "BJV;@", "BJV;@");
      int int0 = appt0.getStartHour();
      assertEquals((-3149), int0);
      assertEquals(-3149, appt0.getStartMonth());
      assertEquals("BJV;@", appt0.getDescription());
      assertEquals("BJV;@", appt0.getTitle());
      assertEquals(-2266, appt0.getStartYear());
      assertEquals(-3149, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(-3149, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 60, (-196), 31, "K)Hk", "K)Hk");
      String string0 = appt0.getDescription();
      assertEquals("K)Hk", string0);
      assertFalse(appt0.getValid());
      assertEquals("K)Hk", appt0.getTitle());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(31, appt0.getStartYear());
      assertEquals(0, appt0.getStartHour());
      assertEquals(-196, appt0.getStartMonth());
      assertEquals(60, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt(1510, 1510, 1510, 1510, 43, "#)wn@g%E", "#)wn@g%E");
      int int0 = appt0.getStartMonth();
      assertEquals("#)wn@g%E", appt0.getDescription());
      assertEquals(43, appt0.getStartYear());
      assertEquals(1510, appt0.getStartMinute());
      assertEquals(1510, appt0.getStartDay());
      assertEquals(1510, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(1510, int0);
      assertEquals("#)wn@g%E", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt(692, 0, 31, 0, 0, "a[t6-jCi", "a[t6-jCi");
      String string0 = appt0.toString();
      assertEquals(0, appt0.getStartYear());
      assertEquals("a[t6-jCi", appt0.getTitle());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(31, appt0.getStartDay());
      assertEquals("a[t6-jCi", appt0.getDescription());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(692, appt0.getStartHour());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt(14, (-1587), (-1587), (-1587), 0, (String) null, (String) null);
      int int0 = appt0.getStartDay();
      assertEquals(-1587, appt0.getStartMinute());
      assertEquals(-1587, appt0.getStartMonth());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals((-1587), int0);
      assertEquals(14, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 60, (-196), 31, "K)Hk", "K)Hk");
      assertEquals("K)Hk", appt0.getTitle());
      
      appt0.setTitle((String) null);
      assertEquals(0, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 0, 0, 11, "", "");
      appt0.setStartDay(11);
      appt0.setStartMonth(89);
      assertEquals(89, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 60, (-196), 31, "K)Hk", "K)Hk");
      assertEquals(60, appt0.getStartDay());
      
      appt0.setStartDay(31);
      assertEquals(31, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt(0, (-284), (-284), 0, 4162, "AllFieldsNull", "5IRV$a$Imm{MTFViQ");
      int int0 = appt0.getStartMinute();
      assertEquals(-284, appt0.getStartDay());
      assertEquals("5IRV$a$Imm{MTFViQ", appt0.getDescription());
      assertEquals(0, appt0.getStartHour());
      assertEquals((-284), int0);
      assertEquals(4162, appt0.getStartYear());
      assertEquals("AllFieldsNull", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt((-790), 0, 0, 2916, (-790), "1903-03-01T00:00:00Z", "kr*0Q!N");
      int int0 = appt0.getStartYear();
      assertEquals(0, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartDay());
      assertEquals("1903-03-01T00:00:00Z", appt0.getTitle());
      assertEquals(-790, appt0.getStartHour());
      assertEquals("kr*0Q!N", appt0.getDescription());
      assertEquals((-790), int0);
      assertEquals(2916, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(692, 0, 31, 0, 0, "a[t6-jCi", "a[t6-jCi");
      appt0.setStartYear(0);
      assertEquals(31, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(692, appt0.getStartHour());
      assertEquals(0, appt0.getStartMonth());
      assertEquals("a[t6-jCi", appt0.getTitle());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMinute());
      assertEquals("a[t6-jCi", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Appt appt0 = new Appt(11, 12, 12, 12, 12, "", "");
      assertEquals(11, appt0.getStartHour());
      
      appt0.setStartHour(12);
      String string0 = appt0.toString();
      assertEquals("\t12/12/12 at 12:12pm ,, \n", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, "pm", "pm");
      String string0 = appt0.toString();
      assertEquals("\t1/1/1 at 1:1am ,pm, pm\n", string0);
      assertNotNull(string0);
  }
}
