/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 01:00:55 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
//import static org.evosuite.runtime.EvoAssertions.*;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CreateASet_ESTest extends CreateASet_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 75 covered goals:
   * Goal 1. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false
   * Goal 2. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - true
   * Goal 3. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I14 Branch 3 IFNE L37 - false
   * Goal 4. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I17 Branch 4 IFNE L37 - true
   * Goal 5. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I41 Branch 5 IF_ICMPGE L42 - true
   * Goal 6. CreateASet.noNulls([Ljava/lang/Object;)Z: I3 Branch 9 IFNE L64 - false
   * Goal 7. CreateASet.noNulls([Ljava/lang/Object;)Z: I5 Branch 10 IFNONNULL L64 - true
   * Goal 8. CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - false
   * Goal 9. CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - true
   * Goal 10. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 11. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 12. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I17 Branch 4 IFNE L37 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 13. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I14 Branch 3 IFNE L37 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 14. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I41 Branch 5 IF_ICMPGE L42 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 15. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I3 Branch 9 IFNE L64 - false in context: 
   * Goal 16. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I5 Branch 10 IFNONNULL L64 - true in context: 
   * Goal 17. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - false in context: 
   * Goal 18. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - true in context: 
   * Goal 19. [Output]: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:EmptyArray
   * Goal 20. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 36
   * Goal 21. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 37
   * Goal 22. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 38
   * Goal 23. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 39
   * Goal 24. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 42
   * Goal 25. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 55
   * Goal 26. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 56
   * Goal 27. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 57
   * Goal 28. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 64
   * Goal 29. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 65
   * Goal 30. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 66
   * Goal 31. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 67
   * Goal 32. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 71
   * Goal 33. [METHOD] CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 34. [METHODNOEX] CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 35. Weak Mutation 76: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - InsertUnaryOp Negation
   * Goal 36. Weak Mutation 77: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != -> ==
   * Goal 37. Weak Mutation 78: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != null -> = null
   * Goal 38. Weak Mutation 80: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - InsertUnaryOp Negation
   * Goal 39. Weak Mutation 81: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceComparisonOperator != -> ==
   * Goal 40. Weak Mutation 82: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceComparisonOperator != -> ==
   * Goal 41. Weak Mutation 84: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:39 - ReplaceConstant - 0 -> 1
   * Goal 42. Weak Mutation 85: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceConstant - 0 -> 1
   * Goal 43. Weak Mutation 87: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp Negation of i
   * Goal 44. Weak Mutation 88: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp IINC 1 i
   * Goal 45. Weak Mutation 89: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp IINC -1 i
   * Goal 46. Weak Mutation 90: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable data -> result
   * Goal 47. Weak Mutation 92: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceComparisonOperator >= -> >
   * Goal 48. Weak Mutation 141: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp Negation of numUnique
   * Goal 49. Weak Mutation 142: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp IINC 1 numUnique
   * Goal 50. Weak Mutation 143: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp IINC -1 numUnique
   * Goal 51. Weak Mutation 144: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result -> data
   * Goal 52. Weak Mutation 145: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result -> result2
   * Goal 53. Weak Mutation 146: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceConstant - 0 -> 1
   * Goal 54. Weak Mutation 147: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result2 -> result
   * Goal 55. Weak Mutation 148: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result2 -> data
   * Goal 56. Weak Mutation 149: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceConstant - 0 -> 1
   * Goal 57. Weak Mutation 150: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - InsertUnaryOp Negation of numUnique
   * Goal 58. Weak Mutation 151: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:57 - ReplaceVariable result2 -> result
   * Goal 59. Weak Mutation 152: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:57 - ReplaceVariable result2 -> data
   * Goal 60. Weak Mutation 153: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - InsertUnaryOp Negation
   * Goal 61. Weak Mutation 154: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - ReplaceComparisonOperator != -> ==
   * Goal 62. Weak Mutation 155: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - ReplaceComparisonOperator != null -> = null
   * Goal 63. Weak Mutation 157: CreateASet.noNulls([Ljava/lang/Object;)Z:65 - ReplaceConstant - 1 -> 0
   * Goal 64. Weak Mutation 158: CreateASet.noNulls([Ljava/lang/Object;)Z:66 - ReplaceConstant - 0 -> 1
   * Goal 65. Weak Mutation 159: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp Negation of good
   * Goal 66. Weak Mutation 160: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC 1 good
   * Goal 67. Weak Mutation 161: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC -1 good
   * Goal 68. Weak Mutation 162: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator == -> !=
   * Goal 69. Weak Mutation 163: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp Negation of i
   * Goal 70. Weak Mutation 164: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC 1 i
   * Goal 71. Weak Mutation 165: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC -1 i
   * Goal 72. Weak Mutation 167: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator >= -> >
   * Goal 73. Weak Mutation 175: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp Negation of good
   * Goal 74. Weak Mutation 176: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp IINC 1 good
   * Goal 75. Weak Mutation 177: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp IINC -1 good
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Object[] objectArray0 = CreateASet.makeSet(stringArray0);
      assertNotNull(objectArray0);
  }

  //Test case number: 1
  /*
   * 59 covered goals:
   * Goal 1. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false
   * Goal 2. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - true
   * Goal 3. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I14 Branch 3 IFNE L37 - false
   * Goal 4. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I17 Branch 4 IFNE L37 - false
   * Goal 5. CreateASet.noNulls([Ljava/lang/Object;)Z: I3 Branch 9 IFNE L64 - false
   * Goal 6. CreateASet.noNulls([Ljava/lang/Object;)Z: I5 Branch 10 IFNONNULL L64 - true
   * Goal 7. CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - true
   * Goal 8. CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - false
   * Goal 9. CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - false
   * Goal 10. CreateASet.noNulls([Ljava/lang/Object;)Z: I32 Branch 13 IFNULL L68 - true
   * Goal 11. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 12. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 13. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I17 Branch 4 IFNE L37 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 14. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I14 Branch 3 IFNE L37 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 15. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I3 Branch 9 IFNE L64 - false in context: 
   * Goal 16. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I5 Branch 10 IFNONNULL L64 - true in context: 
   * Goal 17. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - true in context: 
   * Goal 18. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - false in context: 
   * Goal 19. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - false in context: 
   * Goal 20. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I32 Branch 13 IFNULL L68 - true in context: 
   * Goal 21. makeSet([Ljava/lang/Object;)[Ljava/lang/Object;_java.lang.AssertionError_EXPLICIT
   * Goal 22. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 36
   * Goal 23. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 37
   * Goal 24. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 64
   * Goal 25. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 65
   * Goal 26. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 66
   * Goal 27. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 67
   * Goal 28. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 68
   * Goal 29. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 69
   * Goal 30. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 71
   * Goal 31. [METHOD] CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 32. Weak Mutation 76: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - InsertUnaryOp Negation
   * Goal 33. Weak Mutation 77: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != -> ==
   * Goal 34. Weak Mutation 78: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != null -> = null
   * Goal 35. Weak Mutation 80: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - InsertUnaryOp Negation
   * Goal 36. Weak Mutation 81: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceComparisonOperator != -> ==
   * Goal 37. Weak Mutation 82: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceComparisonOperator != -> ==
   * Goal 38. Weak Mutation 83: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceConstant - Failed precondition makeSet. no elements of parameter can be null -> 
   * Goal 39. Weak Mutation 153: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - InsertUnaryOp Negation
   * Goal 40. Weak Mutation 154: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - ReplaceComparisonOperator != -> ==
   * Goal 41. Weak Mutation 155: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - ReplaceComparisonOperator != null -> = null
   * Goal 42. Weak Mutation 157: CreateASet.noNulls([Ljava/lang/Object;)Z:65 - ReplaceConstant - 1 -> 0
   * Goal 43. Weak Mutation 158: CreateASet.noNulls([Ljava/lang/Object;)Z:66 - ReplaceConstant - 0 -> 1
   * Goal 44. Weak Mutation 159: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp Negation of good
   * Goal 45. Weak Mutation 160: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC 1 good
   * Goal 46. Weak Mutation 161: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC -1 good
   * Goal 47. Weak Mutation 162: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator == -> !=
   * Goal 48. Weak Mutation 163: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp Negation of i
   * Goal 49. Weak Mutation 164: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC 1 i
   * Goal 50. Weak Mutation 165: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC -1 i
   * Goal 51. Weak Mutation 166: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator >= -> -1
   * Goal 52. Weak Mutation 169: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp Negation of i
   * Goal 53. Weak Mutation 170: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp IINC 1 i
   * Goal 54. Weak Mutation 171: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp IINC -1 i
   * Goal 55. Weak Mutation 172: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - ReplaceComparisonOperator = null -> != null
   * Goal 56. Weak Mutation 174: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - ReplaceConstant - 0 -> 1
   * Goal 57. Weak Mutation 175: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp Negation of good
   * Goal 58. Weak Mutation 176: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp IINC 1 good
   * Goal 59. Weak Mutation 177: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp IINC -1 good
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[10];
      // Undeclared exception!
      try { 
        CreateASet.makeSet(stringArray0);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // Failed precondition makeSet. no elements of parameter can be null
         //
      }
  }

  //Test case number: 2
  /*
   * 11 covered goals:
   * Goal 1. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false
   * Goal 2. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - false
   * Goal 3. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 4. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 5. makeSet([Ljava/lang/Object;)[Ljava/lang/Object;_java.lang.AssertionError_EXPLICIT
   * Goal 6. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 36
   * Goal 7. [METHOD] CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 8. Weak Mutation 76: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - InsertUnaryOp Negation
   * Goal 9. Weak Mutation 77: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != -> ==
   * Goal 10. Weak Mutation 78: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != null -> = null
   * Goal 11. Weak Mutation 79: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceConstant - Failed precondition makeSet. parameter cannot be null -> 
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        CreateASet.makeSet((Object[]) null);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // Failed precondition makeSet. parameter cannot be null
         //
      }
  }

  //Test case number: 3
  /*
   * 231 covered goals:
   * Goal 1. CreateASet.main([Ljava/lang/String;)V: root-Branch
   * Goal 2. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false
   * Goal 3. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - true
   * Goal 4. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I14 Branch 3 IFNE L37 - false
   * Goal 5. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I17 Branch 4 IFNE L37 - true
   * Goal 6. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I41 Branch 5 IF_ICMPGE L42 - true
   * Goal 7. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I41 Branch 5 IF_ICMPGE L42 - false
   * Goal 8. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I53 Branch 6 IFNE L46 - true
   * Goal 9. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I53 Branch 6 IFNE L46 - false
   * Goal 10. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I56 Branch 7 IF_ICMPGE L46 - true
   * Goal 11. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I56 Branch 7 IF_ICMPGE L46 - false
   * Goal 12. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I74 Branch 8 IFNE L50 - true
   * Goal 13. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I74 Branch 8 IFNE L50 - false
   * Goal 14. CreateASet.noNulls([Ljava/lang/Object;)Z: I3 Branch 9 IFNE L64 - false
   * Goal 15. CreateASet.noNulls([Ljava/lang/Object;)Z: I5 Branch 10 IFNONNULL L64 - true
   * Goal 16. CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - false
   * Goal 17. CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - true
   * Goal 18. CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - false
   * Goal 19. CreateASet.noNulls([Ljava/lang/Object;)Z: I32 Branch 13 IFNULL L68 - false
   * Goal 20. Branch CreateASet.main([Ljava/lang/String;)V: root-Branch in context: CreateASet:main([Ljava/lang/String;)V
   * Goal 21. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I3 Branch 9 IFNE L64 - false in context: 
   * Goal 22. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I5 Branch 10 IFNONNULL L64 - true in context: 
   * Goal 23. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - false in context: 
   * Goal 24. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - false in context: 
   * Goal 25. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - true in context: 
   * Goal 26. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I32 Branch 13 IFNULL L68 - false in context: 
   * Goal 27. CreateASet.main([Ljava/lang/String;)V: Line 12
   * Goal 28. CreateASet.main([Ljava/lang/String;)V: Line 13
   * Goal 29. CreateASet.main([Ljava/lang/String;)V: Line 14
   * Goal 30. CreateASet.main([Ljava/lang/String;)V: Line 16
   * Goal 31. CreateASet.main([Ljava/lang/String;)V: Line 18
   * Goal 32. CreateASet.main([Ljava/lang/String;)V: Line 19
   * Goal 33. CreateASet.main([Ljava/lang/String;)V: Line 22
   * Goal 34. CreateASet.main([Ljava/lang/String;)V: Line 24
   * Goal 35. CreateASet.main([Ljava/lang/String;)V: Line 25
   * Goal 36. CreateASet.main([Ljava/lang/String;)V: Line 26
   * Goal 37. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 36
   * Goal 38. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 37
   * Goal 39. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 38
   * Goal 40. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 39
   * Goal 41. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 42
   * Goal 42. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 44
   * Goal 43. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 45
   * Goal 44. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 46
   * Goal 45. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 47
   * Goal 46. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 48
   * Goal 47. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 50
   * Goal 48. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 51
   * Goal 49. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 52
   * Goal 50. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 55
   * Goal 51. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 56
   * Goal 52. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 57
   * Goal 53. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 64
   * Goal 54. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 65
   * Goal 55. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 66
   * Goal 56. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 67
   * Goal 57. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 68
   * Goal 58. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 69
   * Goal 59. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 71
   * Goal 60. [METHOD] CreateASet.main([Ljava/lang/String;)V
   * Goal 61. [METHODNOEX] CreateASet.main([Ljava/lang/String;)V
   * Goal 62. Weak Mutation 0: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 6 -> 0
   * Goal 63. Weak Mutation 1: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 6 -> 1
   * Goal 64. Weak Mutation 2: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 6 -> -1
   * Goal 65. Weak Mutation 3: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 6 -> 5
   * Goal 66. Weak Mutation 4: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 6 -> 7
   * Goal 67. Weak Mutation 5: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 0 -> 1
   * Goal 68. Weak Mutation 6: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - A -> 
   * Goal 69. Weak Mutation 7: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 1 -> 0
   * Goal 70. Weak Mutation 8: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - B -> 
   * Goal 71. Weak Mutation 9: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 2 -> 0
   * Goal 72. Weak Mutation 10: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 2 -> 1
   * Goal 73. Weak Mutation 11: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 2 -> -1
   * Goal 74. Weak Mutation 12: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 2 -> 3
   * Goal 75. Weak Mutation 13: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - B -> 
   * Goal 76. Weak Mutation 14: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 3 -> 0
   * Goal 77. Weak Mutation 15: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 3 -> 1
   * Goal 78. Weak Mutation 16: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 3 -> -1
   * Goal 79. Weak Mutation 17: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 3 -> 2
   * Goal 80. Weak Mutation 18: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 3 -> 4
   * Goal 81. Weak Mutation 19: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - D -> 
   * Goal 82. Weak Mutation 20: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 4 -> 0
   * Goal 83. Weak Mutation 21: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 4 -> 1
   * Goal 84. Weak Mutation 22: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 4 -> -1
   * Goal 85. Weak Mutation 23: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 4 -> 3
   * Goal 86. Weak Mutation 24: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 4 -> 5
   * Goal 87. Weak Mutation 25: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - C -> 
   * Goal 88. Weak Mutation 26: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 5 -> 0
   * Goal 89. Weak Mutation 27: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 5 -> 1
   * Goal 90. Weak Mutation 28: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 5 -> -1
   * Goal 91. Weak Mutation 29: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 5 -> 4
   * Goal 92. Weak Mutation 30: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - 5 -> 6
   * Goal 93. Weak Mutation 31: CreateASet.main([Ljava/lang/String;)V:12 - ReplaceConstant - A -> 
   * Goal 94. Weak Mutation 32: CreateASet.main([Ljava/lang/String;)V:13 - ReplaceConstant - original:  -> 
   * Goal 95. Weak Mutation 33: CreateASet.main([Ljava/lang/String;)V:13 - ReplaceVariable words -> args
   * Goal 96. Weak Mutation 34: CreateASet.main([Ljava/lang/String;)V:14 - ReplaceConstant - as a set:  -> 
   * Goal 97. Weak Mutation 35: CreateASet.main([Ljava/lang/String;)V:14 - ReplaceVariable words -> args
   * Goal 98. Weak Mutation 36: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 4 -> 0
   * Goal 99. Weak Mutation 37: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 4 -> 1
   * Goal 100. Weak Mutation 38: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 4 -> -1
   * Goal 101. Weak Mutation 39: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 4 -> 3
   * Goal 102. Weak Mutation 40: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 4 -> 5
   * Goal 103. Weak Mutation 41: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 0 -> 1
   * Goal 104. Weak Mutation 42: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 1 -> 0
   * Goal 105. Weak Mutation 43: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 0
   * Goal 106. Weak Mutation 44: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 1
   * Goal 107. Weak Mutation 45: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> -1
   * Goal 108. Weak Mutation 46: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 3
   * Goal 109. Weak Mutation 47: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 0 -> 1
   * Goal 110. Weak Mutation 48: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 1 -> 0
   * Goal 111. Weak Mutation 49: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 0
   * Goal 112. Weak Mutation 50: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 1
   * Goal 113. Weak Mutation 51: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> -1
   * Goal 114. Weak Mutation 52: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 3
   * Goal 115. Weak Mutation 53: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 0
   * Goal 116. Weak Mutation 54: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 1
   * Goal 117. Weak Mutation 55: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> -1
   * Goal 118. Weak Mutation 56: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 2
   * Goal 119. Weak Mutation 57: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 4
   * Goal 120. Weak Mutation 58: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 0
   * Goal 121. Weak Mutation 59: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 1
   * Goal 122. Weak Mutation 60: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> -1
   * Goal 123. Weak Mutation 61: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 2
   * Goal 124. Weak Mutation 62: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 4
   * Goal 125. Weak Mutation 63: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 0 -> 1
   * Goal 126. Weak Mutation 64: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 1 -> 0
   * Goal 127. Weak Mutation 65: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 0
   * Goal 128. Weak Mutation 66: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 1
   * Goal 129. Weak Mutation 67: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> -1
   * Goal 130. Weak Mutation 68: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 2 -> 3
   * Goal 131. Weak Mutation 69: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 0
   * Goal 132. Weak Mutation 70: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 1
   * Goal 133. Weak Mutation 71: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> -1
   * Goal 134. Weak Mutation 72: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 2
   * Goal 135. Weak Mutation 73: CreateASet.main([Ljava/lang/String;)V:16 - ReplaceConstant - 3 -> 4
   * Goal 136. Weak Mutation 74: CreateASet.main([Ljava/lang/String;)V:18 - ReplaceConstant - original:  -> 
   * Goal 137. Weak Mutation 75: CreateASet.main([Ljava/lang/String;)V:19 - ReplaceConstant - as a set:  -> 
   * Goal 138. Weak Mutation 76: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - InsertUnaryOp Negation
   * Goal 139. Weak Mutation 77: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != -> ==
   * Goal 140. Weak Mutation 78: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != null -> = null
   * Goal 141. Weak Mutation 80: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - InsertUnaryOp Negation
   * Goal 142. Weak Mutation 81: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceComparisonOperator != -> ==
   * Goal 143. Weak Mutation 82: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceComparisonOperator != -> ==
   * Goal 144. Weak Mutation 84: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:39 - ReplaceConstant - 0 -> 1
   * Goal 145. Weak Mutation 85: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceConstant - 0 -> 1
   * Goal 146. Weak Mutation 86: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable i -> numUnique
   * Goal 147. Weak Mutation 87: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp Negation of i
   * Goal 148. Weak Mutation 88: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp IINC 1 i
   * Goal 149. Weak Mutation 89: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp IINC -1 i
   * Goal 150. Weak Mutation 90: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable data -> result
   * Goal 151. Weak Mutation 91: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceComparisonOperator >= -> -1
   * Goal 152. Weak Mutation 92: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceComparisonOperator >= -> >
   * Goal 153. Weak Mutation 139: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable i -> numUnique
   * Goal 154. Weak Mutation 140: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable i -> indexInResult
   * Goal 155. Weak Mutation 94: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:44 - ReplaceConstant - 0 -> 1
   * Goal 156. Weak Mutation 95: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:45 - ReplaceConstant - 0 -> 1
   * Goal 157. Weak Mutation 96: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp Negation of found
   * Goal 158. Weak Mutation 97: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceComparisonOperator != -> ==
   * Goal 159. Weak Mutation 98: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceVariable indexInResult -> numUnique
   * Goal 160. Weak Mutation 99: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceVariable indexInResult -> i
   * Goal 161. Weak Mutation 100: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp Negation of indexInResult
   * Goal 162. Weak Mutation 101: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceVariable numUnique -> indexInResult
   * Goal 163. Weak Mutation 102: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceVariable numUnique -> i
   * Goal 164. Weak Mutation 103: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp Negation of numUnique
   * Goal 165. Weak Mutation 104: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp IINC 1 numUnique
   * Goal 166. Weak Mutation 105: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp IINC -1 numUnique
   * Goal 167. Weak Mutation 106: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceComparisonOperator >= -> -1
   * Goal 168. Weak Mutation 107: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceComparisonOperator >= -> >
   * Goal 169. Weak Mutation 109: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable data -> result
   * Goal 170. Weak Mutation 110: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable i -> numUnique
   * Goal 171. Weak Mutation 111: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable i -> indexInResult
   * Goal 172. Weak Mutation 112: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp Negation of i
   * Goal 173. Weak Mutation 113: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp IINC 1 i
   * Goal 174. Weak Mutation 114: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp IINC -1 i
   * Goal 175. Weak Mutation 115: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable result -> data
   * Goal 176. Weak Mutation 116: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable indexInResult -> numUnique
   * Goal 177. Weak Mutation 117: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable indexInResult -> i
   * Goal 178. Weak Mutation 118: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp Negation of indexInResult
   * Goal 179. Weak Mutation 119: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp IINC 1 indexInResult
   * Goal 180. Weak Mutation 120: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp IINC -1 indexInResult
   * Goal 181. Weak Mutation 121: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:48 - ReplaceVariable indexInResult -> numUnique
   * Goal 182. Weak Mutation 122: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:48 - ReplaceVariable indexInResult -> i
   * Goal 183. Weak Mutation 123: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:50 - InsertUnaryOp Negation of found
   * Goal 184. Weak Mutation 124: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:50 - ReplaceComparisonOperator != -> ==
   * Goal 185. Weak Mutation 125: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - ReplaceVariable result -> data
   * Goal 186. Weak Mutation 127: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - ReplaceVariable numUnique -> i
   * Goal 187. Weak Mutation 128: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp Negation of numUnique
   * Goal 188. Weak Mutation 129: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp IINC 1 numUnique
   * Goal 189. Weak Mutation 130: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp IINC -1 numUnique
   * Goal 190. Weak Mutation 131: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - ReplaceVariable data -> result
   * Goal 191. Weak Mutation 132: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - ReplaceVariable i -> numUnique
   * Goal 192. Weak Mutation 133: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - ReplaceVariable i -> indexInResult
   * Goal 193. Weak Mutation 134: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp Negation of i
   * Goal 194. Weak Mutation 135: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp IINC 1 i
   * Goal 195. Weak Mutation 136: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp IINC -1 i
   * Goal 196. Weak Mutation 137: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:52 - ReplaceVariable numUnique -> indexInResult
   * Goal 197. Weak Mutation 138: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:52 - ReplaceVariable numUnique -> i
   * Goal 198. Weak Mutation 141: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp Negation of numUnique
   * Goal 199. Weak Mutation 142: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp IINC 1 numUnique
   * Goal 200. Weak Mutation 143: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp IINC -1 numUnique
   * Goal 201. Weak Mutation 144: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result -> data
   * Goal 202. Weak Mutation 145: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result -> result2
   * Goal 203. Weak Mutation 146: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceConstant - 0 -> 1
   * Goal 204. Weak Mutation 147: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result2 -> result
   * Goal 205. Weak Mutation 148: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result2 -> data
   * Goal 206. Weak Mutation 149: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceConstant - 0 -> 1
   * Goal 207. Weak Mutation 150: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - InsertUnaryOp Negation of numUnique
   * Goal 208. Weak Mutation 151: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:57 - ReplaceVariable result2 -> result
   * Goal 209. Weak Mutation 152: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:57 - ReplaceVariable result2 -> data
   * Goal 210. Weak Mutation 153: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - InsertUnaryOp Negation
   * Goal 211. Weak Mutation 154: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - ReplaceComparisonOperator != -> ==
   * Goal 212. Weak Mutation 155: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - ReplaceComparisonOperator != null -> = null
   * Goal 213. Weak Mutation 157: CreateASet.noNulls([Ljava/lang/Object;)Z:65 - ReplaceConstant - 1 -> 0
   * Goal 214. Weak Mutation 158: CreateASet.noNulls([Ljava/lang/Object;)Z:66 - ReplaceConstant - 0 -> 1
   * Goal 215. Weak Mutation 159: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp Negation of good
   * Goal 216. Weak Mutation 160: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC 1 good
   * Goal 217. Weak Mutation 161: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC -1 good
   * Goal 218. Weak Mutation 162: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator == -> !=
   * Goal 219. Weak Mutation 163: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp Negation of i
   * Goal 220. Weak Mutation 164: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC 1 i
   * Goal 221. Weak Mutation 165: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC -1 i
   * Goal 222. Weak Mutation 166: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator >= -> -1
   * Goal 223. Weak Mutation 167: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator >= -> >
   * Goal 224. Weak Mutation 169: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp Negation of i
   * Goal 225. Weak Mutation 170: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp IINC 1 i
   * Goal 226. Weak Mutation 171: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp IINC -1 i
   * Goal 227. Weak Mutation 172: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - ReplaceComparisonOperator = null -> != null
   * Goal 228. Weak Mutation 173: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - ReplaceConstant - 1 -> 0
   * Goal 229. Weak Mutation 175: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp Negation of good
   * Goal 230. Weak Mutation 176: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp IINC 1 good
   * Goal 231. Weak Mutation 177: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp IINC -1 good
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[0];
      CreateASet.main(stringArray0);
  }

  //Test case number: 4
  /*
   * 157 covered goals:
   * Goal 1. CreateASet.<init>()V: root-Branch
   * Goal 2. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false
   * Goal 3. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - true
   * Goal 4. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I14 Branch 3 IFNE L37 - false
   * Goal 5. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I17 Branch 4 IFNE L37 - true
   * Goal 6. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I41 Branch 5 IF_ICMPGE L42 - true
   * Goal 7. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I41 Branch 5 IF_ICMPGE L42 - false
   * Goal 8. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I53 Branch 6 IFNE L46 - true
   * Goal 9. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I53 Branch 6 IFNE L46 - false
   * Goal 10. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I56 Branch 7 IF_ICMPGE L46 - true
   * Goal 11. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I56 Branch 7 IF_ICMPGE L46 - false
   * Goal 12. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I74 Branch 8 IFNE L50 - true
   * Goal 13. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I74 Branch 8 IFNE L50 - false
   * Goal 14. CreateASet.noNulls([Ljava/lang/Object;)Z: I3 Branch 9 IFNE L64 - false
   * Goal 15. CreateASet.noNulls([Ljava/lang/Object;)Z: I5 Branch 10 IFNONNULL L64 - true
   * Goal 16. CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - false
   * Goal 17. CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - true
   * Goal 18. CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - false
   * Goal 19. CreateASet.noNulls([Ljava/lang/Object;)Z: I32 Branch 13 IFNULL L68 - false
   * Goal 20. Branch CreateASet.<init>()V: root-Branch in context: CreateASet:<init>()V
   * Goal 21. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 1 IFNE L36 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 22. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I5 Branch 2 IFNONNULL L36 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 23. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I17 Branch 4 IFNE L37 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 24. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I14 Branch 3 IFNE L37 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 25. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I41 Branch 5 IF_ICMPGE L42 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 26. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I41 Branch 5 IF_ICMPGE L42 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 27. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I53 Branch 6 IFNE L46 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 28. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I56 Branch 7 IF_ICMPGE L46 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 29. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I56 Branch 7 IF_ICMPGE L46 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 30. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I53 Branch 6 IFNE L46 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 31. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I74 Branch 8 IFNE L50 - false in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 32. Branch CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: I74 Branch 8 IFNE L50 - true in context: CreateASet:makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 33. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I3 Branch 9 IFNE L64 - false in context: 
   * Goal 34. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I5 Branch 10 IFNONNULL L64 - true in context: 
   * Goal 35. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I22 Branch 11 IFEQ L67 - false in context: 
   * Goal 36. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - false in context: 
   * Goal 37. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I26 Branch 12 IF_ICMPGE L67 - true in context: 
   * Goal 38. Branch CreateASet.noNulls([Ljava/lang/Object;)Z: I32 Branch 13 IFNULL L68 - false in context: 
   * Goal 39. [Output]: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:NonEmptyArray
   * Goal 40. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 36
   * Goal 41. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 37
   * Goal 42. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 38
   * Goal 43. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 39
   * Goal 44. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 42
   * Goal 45. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 44
   * Goal 46. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 45
   * Goal 47. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 46
   * Goal 48. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 47
   * Goal 49. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 48
   * Goal 50. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 50
   * Goal 51. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 51
   * Goal 52. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 52
   * Goal 53. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 55
   * Goal 54. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 56
   * Goal 55. CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;: Line 57
   * Goal 56. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 64
   * Goal 57. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 65
   * Goal 58. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 66
   * Goal 59. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 67
   * Goal 60. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 68
   * Goal 61. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 69
   * Goal 62. CreateASet.noNulls([Ljava/lang/Object;)Z: Line 71
   * Goal 63. [METHOD] CreateASet.<init>()V
   * Goal 64. [METHOD] CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 65. [METHODNOEX] CreateASet.<init>()V
   * Goal 66. [METHODNOEX] CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 67. Weak Mutation 76: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - InsertUnaryOp Negation
   * Goal 68. Weak Mutation 77: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != -> ==
   * Goal 69. Weak Mutation 78: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:36 - ReplaceComparisonOperator != null -> = null
   * Goal 70. Weak Mutation 80: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - InsertUnaryOp Negation
   * Goal 71. Weak Mutation 81: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceComparisonOperator != -> ==
   * Goal 72. Weak Mutation 82: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:37 - ReplaceComparisonOperator != -> ==
   * Goal 73. Weak Mutation 84: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:39 - ReplaceConstant - 0 -> 1
   * Goal 74. Weak Mutation 85: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceConstant - 0 -> 1
   * Goal 75. Weak Mutation 86: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable i -> numUnique
   * Goal 76. Weak Mutation 87: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp Negation of i
   * Goal 77. Weak Mutation 88: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp IINC 1 i
   * Goal 78. Weak Mutation 89: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - InsertUnaryOp IINC -1 i
   * Goal 79. Weak Mutation 90: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable data -> result
   * Goal 80. Weak Mutation 91: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceComparisonOperator >= -> -1
   * Goal 81. Weak Mutation 92: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceComparisonOperator >= -> >
   * Goal 82. Weak Mutation 139: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable i -> numUnique
   * Goal 83. Weak Mutation 140: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:42 - ReplaceVariable i -> indexInResult
   * Goal 84. Weak Mutation 94: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:44 - ReplaceConstant - 0 -> 1
   * Goal 85. Weak Mutation 95: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:45 - ReplaceConstant - 0 -> 1
   * Goal 86. Weak Mutation 96: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp Negation of found
   * Goal 87. Weak Mutation 97: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceComparisonOperator != -> ==
   * Goal 88. Weak Mutation 98: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceVariable indexInResult -> numUnique
   * Goal 89. Weak Mutation 99: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceVariable indexInResult -> i
   * Goal 90. Weak Mutation 100: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp Negation of indexInResult
   * Goal 91. Weak Mutation 101: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceVariable numUnique -> indexInResult
   * Goal 92. Weak Mutation 102: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceVariable numUnique -> i
   * Goal 93. Weak Mutation 103: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp Negation of numUnique
   * Goal 94. Weak Mutation 104: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp IINC 1 numUnique
   * Goal 95. Weak Mutation 105: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - InsertUnaryOp IINC -1 numUnique
   * Goal 96. Weak Mutation 106: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceComparisonOperator >= -> -1
   * Goal 97. Weak Mutation 107: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:46 - ReplaceComparisonOperator >= -> >
   * Goal 98. Weak Mutation 109: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable data -> result
   * Goal 99. Weak Mutation 110: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable i -> numUnique
   * Goal 100. Weak Mutation 111: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable i -> indexInResult
   * Goal 101. Weak Mutation 112: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp Negation of i
   * Goal 102. Weak Mutation 113: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp IINC 1 i
   * Goal 103. Weak Mutation 114: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp IINC -1 i
   * Goal 104. Weak Mutation 115: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable result -> data
   * Goal 105. Weak Mutation 116: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable indexInResult -> numUnique
   * Goal 106. Weak Mutation 117: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - ReplaceVariable indexInResult -> i
   * Goal 107. Weak Mutation 118: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp Negation of indexInResult
   * Goal 108. Weak Mutation 119: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp IINC 1 indexInResult
   * Goal 109. Weak Mutation 120: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:47 - InsertUnaryOp IINC -1 indexInResult
   * Goal 110. Weak Mutation 121: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:48 - ReplaceVariable indexInResult -> numUnique
   * Goal 111. Weak Mutation 122: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:48 - ReplaceVariable indexInResult -> i
   * Goal 112. Weak Mutation 123: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:50 - InsertUnaryOp Negation of found
   * Goal 113. Weak Mutation 124: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:50 - ReplaceComparisonOperator != -> ==
   * Goal 114. Weak Mutation 125: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - ReplaceVariable result -> data
   * Goal 115. Weak Mutation 128: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp Negation of numUnique
   * Goal 116. Weak Mutation 129: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp IINC 1 numUnique
   * Goal 117. Weak Mutation 130: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp IINC -1 numUnique
   * Goal 118. Weak Mutation 131: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - ReplaceVariable data -> result
   * Goal 119. Weak Mutation 134: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp Negation of i
   * Goal 120. Weak Mutation 135: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp IINC 1 i
   * Goal 121. Weak Mutation 136: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:51 - InsertUnaryOp IINC -1 i
   * Goal 122. Weak Mutation 137: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:52 - ReplaceVariable numUnique -> indexInResult
   * Goal 123. Weak Mutation 138: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:52 - ReplaceVariable numUnique -> i
   * Goal 124. Weak Mutation 141: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp Negation of numUnique
   * Goal 125. Weak Mutation 142: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp IINC 1 numUnique
   * Goal 126. Weak Mutation 143: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:55 - InsertUnaryOp IINC -1 numUnique
   * Goal 127. Weak Mutation 144: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result -> data
   * Goal 128. Weak Mutation 145: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result -> result2
   * Goal 129. Weak Mutation 146: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceConstant - 0 -> 1
   * Goal 130. Weak Mutation 147: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result2 -> result
   * Goal 131. Weak Mutation 148: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceVariable result2 -> data
   * Goal 132. Weak Mutation 149: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - ReplaceConstant - 0 -> 1
   * Goal 133. Weak Mutation 150: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:56 - InsertUnaryOp Negation of numUnique
   * Goal 134. Weak Mutation 151: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:57 - ReplaceVariable result2 -> result
   * Goal 135. Weak Mutation 152: CreateASet.makeSet([Ljava/lang/Object;)[Ljava/lang/Object;:57 - ReplaceVariable result2 -> data
   * Goal 136. Weak Mutation 153: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - InsertUnaryOp Negation
   * Goal 137. Weak Mutation 154: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - ReplaceComparisonOperator != -> ==
   * Goal 138. Weak Mutation 155: CreateASet.noNulls([Ljava/lang/Object;)Z:64 - ReplaceComparisonOperator != null -> = null
   * Goal 139. Weak Mutation 157: CreateASet.noNulls([Ljava/lang/Object;)Z:65 - ReplaceConstant - 1 -> 0
   * Goal 140. Weak Mutation 158: CreateASet.noNulls([Ljava/lang/Object;)Z:66 - ReplaceConstant - 0 -> 1
   * Goal 141. Weak Mutation 159: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp Negation of good
   * Goal 142. Weak Mutation 160: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC 1 good
   * Goal 143. Weak Mutation 161: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC -1 good
   * Goal 144. Weak Mutation 162: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator == -> !=
   * Goal 145. Weak Mutation 163: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp Negation of i
   * Goal 146. Weak Mutation 164: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC 1 i
   * Goal 147. Weak Mutation 165: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - InsertUnaryOp IINC -1 i
   * Goal 148. Weak Mutation 166: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator >= -> -1
   * Goal 149. Weak Mutation 167: CreateASet.noNulls([Ljava/lang/Object;)Z:67 - ReplaceComparisonOperator >= -> >
   * Goal 150. Weak Mutation 169: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp Negation of i
   * Goal 151. Weak Mutation 170: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp IINC 1 i
   * Goal 152. Weak Mutation 171: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - InsertUnaryOp IINC -1 i
   * Goal 153. Weak Mutation 172: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - ReplaceComparisonOperator = null -> != null
   * Goal 154. Weak Mutation 173: CreateASet.noNulls([Ljava/lang/Object;)Z:68 - ReplaceConstant - 1 -> 0
   * Goal 155. Weak Mutation 175: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp Negation of good
   * Goal 156. Weak Mutation 176: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp IINC 1 good
   * Goal 157. Weak Mutation 177: CreateASet.noNulls([Ljava/lang/Object;)Z:71 - InsertUnaryOp IINC -1 good
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CreateASet createASet0 = new CreateASet();
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) createASet0;
      objectArray0[1] = (Object) createASet0;
      objectArray0[2] = (Object) createASet0;
      objectArray0[3] = (Object) createASet0;
      objectArray0[4] = (Object) createASet0;
      objectArray0[5] = (Object) createASet0;
      Object[] objectArray1 = CreateASet.makeSet(objectArray0);
      assertNotSame(objectArray1, objectArray0);
  }
}
